#
# Home Assistant Automation Blueprint
#
# Sends three notifications to an Amazon Echo device to close a window or door after opening it,
# if the humidity reading (indoor) and temperature reading (outdoor) of the given sensors are below a certain level.
# For this blueprint you need a a working Alexa Media Player Integration, and a humidity sensor that updates its data in short intervalls.
# Most likely it needs a wired power connection for this. A working configuration is the SONOFF TH Sensor Si7021 connected to a Sonoff TH10.
#
# Revision 1.3 (04.01.2022):
# New option to set the volume
# Based on https://github.com/home-IoT/hass-blueprints/blob/main/reminder_to_close_window_with_temp_sensor.yaml
#

blueprint:
  name: "Echo-Notification to Close a Window with custom sensors"
  description: Notification by Alexa to close windows if the humidity inside is below a given value. For this blueprint you need a a working Alexa Media Player Integration, and a humidity sensor that updates its data in short intervalls. Most likely it needs a wired power connection for this. A working configuration is the SONOFF TH Sensor Si7021 connected to a Sonoff TH10.

  domain: automation
  input:
    contact_sensor:
      name: Contact Sensor
      description: "The window or door sensor that triggers the automation."
      selector:
        entity:
          domain: binary_sensor
    temperature_sensor:
      name: Temperature Sensor
      description: "The sensor used for reading the outside temperature."
      selector:
        entity:
          domain: sensor
          device_class: temperature
    temperature:
      name: Temperature
      description: "The outside temperature below which the notification should be sent."
      default: 20
      selector:
        number:
          min: 0
          step: 1
          max: 50
          mode: slider
    first_timer:
      name: First timer
      description: "The first notification timer (in minutes). The time starts after opening the window."
      default: 10
      selector:
        number:
          min: 1
          step: 1
          max: 60
          mode: slider
    second_timer:
      name: Second timer
      description: "The second notification timer (in minutes). The time starts after opening the window."
      default: 15
      selector:
        number:
          min: 1
          step: 1
          max: 60
          mode: slider
    third_timer:
      name: Third timer
      description: "The third notification timer (in minutes). The time starts after opening the window."
      default: 20
      selector:
        number:
          min: 1
          step: 1
          max: 60
          mode: slider
    message:
      name: Message
      description: "Change the message Alexa will speak."
      default: Time to close your window.
      selector:
        text:
          multiline: true
    echo:
      name: "Echo device"
      description: "Write the device name of the echo you want to use. Something like media_player.echo_bathroom."
      selector:
        text:
    volume-message:
      name: Volume of the message
      description: "Set the volume of the message"
      default: 0.6
      selector:
        number:
          min: 0
          step: 0.01
          max: 1
          mode: slider
    volume-after:
      name: Volume after the message
      description: "The volume your Echo device should use, after the message was spoken"
      default: 0.5
      selector:
        number:
          min: 0
          step: 0.01
          max: 1
          mode: slider
# We will have three triggers, for the three different reminders.
# However, a reminder will be ignored if the door or window is already closed by then.
trigger:
  - platform: state
    entity_id: !input contact_sensor
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: !input first_timer
      seconds: 0
  - platform: state
    entity_id: !input contact_sensor
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: !input second_timer
      seconds: 0
  - platform: state
    entity_id: !input contact_sensor
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: !input third_timer
      seconds: 0
# Three conditions:
# 1. The door or window should still be open.
# 2. The outside temperature must be below the set value.
condition:
  - condition: state
    entity_id: !input contact_sensor
    state: "on"
  - condition: numeric_state
    entity_id: !input temperature_sensor
    below: !input temperature
# Send a notification to the Echo device.
action:
  - service: media_player.volume_set
    target:
      entity_id: !input echo
    data:
      volume_level: !input volume-message
  - service: notify.alexa_media
    data:
      message: !input message
      data:
        type: tts
      target: !input echo
  - service: media_player.volume_set
    target:
      entity_id: !input echo
    data:
      volume_level: !input volume-after
mode: single
